### ISSUE TITLE
No SteamLogin Button

### ISSUE THREAD

**Issue by Chrisf98** [noxwyll/Steam-Login-MyBB-1.8#11]
If you want to sign in to your Steam account again on our forums, http://MetalGaming.org/, you need to register again with that Steam account. It doesn't actually register you again, just logs you in.

**Comment by TsunaMoo** [comment]
I cannot test this as your website always gets me to the mobile theme with no way back. The switching back link does not do anything.

Let me know once you fixed that or set my account to the blue theme.
Account name is Tatsuto of the Steak
