### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by RoniJames** [noxwyll/Steam-Login-MyBB-1.8#18]
I added this and whenever i click to register an account it directs me to steam and then when coming back to the forums it gives me Error 500 and doesn't log me in. The page it gives the errors at is misc.php

**Comment by RoniJames** [comment]
MyBB v.1.8.6 btw

**Comment by AnonyBart** [comment]
I got the same error too!

**Comment by TsunaMoo** [comment]
Likely steam experiencing issues.

**Comment by sweepies** [comment]
Also having this issue;

`2016/10/31 04:56:44 [error] 29993#29993: *704 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/main/forums/inc/class_steam.php:213
Stack trace:
#0 /var/www/main/forums/inc/class_steam.php(226): steam->unichrsteam(83)
#1 /var/www/main/forums/inc/class_steam.php(265): steam->steam_unicode_username('Sweepyoface')
#2 /var/www/main/forums/inc/plugins/steamlogin.php(377): steam->get_user_info(Array)
#3 /var/www/main/forums/inc/class_plugins.php(139): steam_output_to_misc('')
#4 /var/www/main/forums/misc.php(27): pluginSystem->run_hooks(Array)
#5 {main}
`

**Comment by TsunaMoo** [comment]
That is a different issue but I will check on it.

**Comment by Un1ted4rmy1** [comment]
I reproduced this... Apparently the bcsub() function (the use of another function from the project: https://github.com/damianb/tf2stats) isn't defined.

**Apache Log told me this:**
PHP Fatal error:  Uncaught Error: Call to undefined function bcsub() in /var/www/html/forums/inc/class_steam.php:102\nStack trace:\n#0 /var/www/html/forums/inc/class_steam.php(294): steam->convert64to32('765611980455568...')\n#1 /var/www/html/forums/inc/plugins/steamlogin.php(377): steam->get_user_info(Array)\n#2 /var/www/html/forums/inc/class_plugins.php(139): steam_output_to_misc('')\n#3 /var/www/html/forums/misc.php(27): pluginSystem->run_hooks(Array)\n#4 {main}\n  thrown in /var/www/html/forums/inc/class_steam.php on line 102

I edited the function with:
```
    function convert64to32($id)
    {
        $result = substr($id, 3) - 61197960265728;
        return (string) $result;
    }
```
and now it works.

**Comment by TsunaMoo** [comment]
Are you sure your edit accurately works?

Also it should be defined unless your php is really old.
http://php.net/manual/en/function.bcsub.php

**Comment by sweepies** [comment]
Oh, I thought I had already replied to this. These errors can be fixed by simply installing the missing modules, `php-mbstring` for my previous issue and `php-bcmath` for the latter.

eg. on Ubuntu,

`apt install php-mbstring php-bcmath`

**Comment by TsunaMoo** [comment]
I decided to switch to the supplied code as it seems simpler and appears to avoid some issues. Hopefully that wont cause any further problem then.

**Comment by Un1ted4rmy1** [comment]
I can confirm this works as I currently use it. If there's any issues, I'll be sure to post it.
