### ISSUE TITLE
Blank page on login

### ISSUE THREAD

**Issue by covey88** [noxwyll/Steam-Login-MyBB-1.8#19]
I just set this up on a new forums site, but when I try to sign in through steam, I get redirected to a blank page and cant sign in.. (blank page comes after I'm redirected to the Sign in through steam page and I click on Sign in)

**Comment by TsunaMoo** [comment]
Strange. A page refresh should solve the issue

**Comment by TsunaMoo** [comment]
Should be solved as likely related to emojis and whitespace
