### ISSUE TITLE
Error while signing in

### ISSUE THREAD

**Issue by OMFGMashiron** [noxwyll/Steam-Login-MyBB-1.8#2]
Parse error: syntax error, unexpected T_FUNCTION in /home/a9811228/public_html/inc/class_steam.php on line 102

on line 102  
$personaname = preg_replace_callback('/\\u([0-9a-fA-F]{4})/', function ($match) {

Does it not support certain symbols maybe?  Ex:ⒷⒹⒼ

**Comment by TsunaMoo** [comment]
caused by older php verison. I have updated the code to work with your version.
It supports all symbols.
