### ISSUE TITLE
Problem Please help

### ISSUE THREAD

**Issue by GoproMgH** [noxwyll/Steam-Login-MyBB-1.8#20]
when trying to use steam login i get this 

Fatal error: Uncaught exception 'ErrorException' with message 'No OpenID Server found at http://steamcommunity.com/openid' in /home/a9949016/public_html/inc/class_lightopenid.php:515 Stack trace: #0 /home/a9949016/public_html/inc/class_lightopenid.php(648): LightOpenID->discover() #1 /home/a9949016/public_html/inc/plugins/steamlogin.php(370): LightOpenID->authUrl() #2 /home/a9949016/public_html/inc/plugins/steamlogin.php(396): steam_redirect() #3 /home/a9949016/public_html/inc/class_plugins.php(139): steam_output_to_misc('') #4 /home/a9949016/public_html/misc.php(25): pluginSystem->run_hooks('misc_start') #5 {main} thrown in /home/a9949016/public_html/inc/class_lightopenid.php on line 515

**Comment by Vizikk** [comment]
Same problem.

**Comment by TsunaMoo** [comment]
This means steam did not respond.
I will need to handle this error appropriately when I find time to update the plugin again.

**Comment by anythinguwant2be** [comment]
Yep same problem.
