### ISSUE TITLE
Steam Login button image broken when MyBB is on domain root

### ISSUE THREAD

**Issue by NickVst** [noxwyll/Steam-Login-MyBB-1.8#26]
The Steam login button image does not load if MyBB is installed on the domain root instead of a subfolder (e.g. website.com/ instead of website.com/forum/).

The issue is that when the plugin is installed, the script takes the MyBB root and prepends `inc/plugins/steamlogin/steam_login_btn.png` for the header. However, with MyBB on the root domain, the address looks like `website.cominc/plugins/steamlogin/steam_login_btn.png`. 

It can be manually fixed by changing the image source on line 156 (and 269 for uninstall) from `{$mybb->settings[\'bburl\']}inc/plugins/steamlogin/steam_login_btn.png` to `{$mybb->settings[\'bburl\']}/inc/plugins/steamlogin/steam_login_btn.png`. I'm not very well versed in PHP, so I'm not sure about the changes this'd have on non-domain root installations of MyBB.

Kind of weird though, I'd expect similar behavior when MyBB isn't on the root (e.g. `website.com/forumsinc/plugins/steamlogin/steam_login_btn.png` ).

**Comment by Theedgeclan2** [comment]
their is alot of stupid people out their so i added a sign in with steam button after they signed it
https://www.theedgeclan.com/images/steam_linked.png

**Comment by TsunaMoo** [comment]
could have sworn that bburl usually carries a / with it. Checking.

**Comment by TsunaMoo** [comment]
fixed,
