### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AceTheGmodGeek** [noxwyll/Steam-Login-MyBB-1.8#3]
I added Steam Authentication to my server, it shows the icons etc, but when i click it it shows "Not Configured The Steam Login plugin hasn't been configured correctly. Please ensure an API key is set in the Configuration settings." I have set it in the class_steam file, can someone help me please?

**Comment by AceTheGmodGeek** [comment]
NVM, Got it fixed, but now i have this error 
PHP Error Message

Parse error: syntax error, unexpected T_FUNCTION in /home/a1411485/public_html/inc/class_steam.php on line 102

**Comment by TsunaMoo** [comment]
caused by older php verison. I have updated the code to work with your version.
