### ISSUE TITLE
Failed on return

### ISSUE THREAD

**Issue by lucifermstarvrc** [noxwyll/Steam-Login-MyBB-1.8#32]
When using the steam login it fails to return and gives me a error for failing to handle the request HTTP EORROR 500 or view the image of the error https://i.gyazo.com/919f6b7acb735544bba8b3c9e01351a8.png

I have checked my installation and everything including the requirement of cURL is installed and enabled and is running.

Try signing up yourself if you want to see what happens www.AuroraServers.org 
but this is the url it directs too if this is any help 

> http://www.auroraservers.org/forum/misc.php?action=steam_return&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197994494206&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561197994494206&openid.return_to=http%3A%2F%2Fwww.auroraservers.org%2Fforum%2Fmisc.php%3Faction%3Dsteam_return&openid.response_nonce=2016-09-19T12%3A07%3A56ZRenTkrvDnihOV8c25soQlforsAs%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=Ip0dPmULmjanXEQzgaYzjYMlLuc%3D

It would be nice to get this working so any help is appreciated! Thank you for reading.

**Comment by TsunaMoo** [comment]
It appears there is an issue with your sever.
