### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pkminer30** [noxwyll/Steam-Login-MyBB-1.8#33]
Hello,

I am considering using this and adapting it to work with an existing steamlogin system where i already have steam names and user data in a forum. 

I am allowed to use these files for this purpose?

It doesn't state if its MIT or LGPL on the license only on zingaburga's files which we wont be using which is a GPLv3 license.

Kind Regards

Jack

**Comment by TsunaMoo** [comment]
I don't think any license was ever stated and I am not in any position to set one. This is a fork to a older plugin. I am merely evolving and maintaining it. You would have to ask the original author of this.
