### ISSUE TITLE
Logging in and registering aren't working

### ISSUE THREAD

**Issue by sanny-io** [noxwyll/Steam-Login-MyBB-1.8#35]
With Ubuntu 14.05.5 LTS, apache2, php5, CURL, MyBB 1.8.7, the API key in place, and both plugins (Display Name + Steam Login) installed and activated, the login and registration process seems to never complete. After logging in through Steam, the user is just redirected to the forum index, not logged in.

Also, after uninstalling the plugin and deleting it completely, the Steam login button is still in the header.

**Comment by ghost** [comment]
You sure you deleted it completely, from inc/plugin folder and all? Could be a cache problem, but i doubt it.

**Comment by sanny-io** [comment]
Yeah, completely deleted from the plugins folder. The image is gone now, but the template seems to still be there, even in incognito mode and on my mobile phone that has never visited the site until now.

![http://i.imgur.com/rwH2vFS.png](http://i.imgur.com/rwH2vFS.png)

This is a fresh install of mybb, too. There were no plugins installed until I uploaded this one. I'm more concerned with the login and registration problems, though, since integrating Steam is important for my forums.

**Comment by ghost** [comment]
Run updates on your server. That sounds like a weird issue to me. Make sure you aren't working in one area when the site is in another. It could also be located in your theme templates or something, You didn't happen to put it there by chance? I'd check templates if nothing was in files at least.

**Comment by TsunaMoo** [comment]
Please reinstall using the newest files.

**Comment by sanny-io** [comment]
Reinstalled completely by deactivating the plugins, deleting their files in the FTP, reuploading, and reactivating. The problem still seems to be there.

**Comment by TsunaMoo** [comment]
Some code updates were made to address some issues with user naming. Please update and verify if the bug is still present.

Additionally check your web server for any non-standard configurations.
Ensure your cookies are set correctly and that curl is supported.

**Comment by sanny-io** [comment]
The web server config looks fine. Cookies are okay and work normally for the default mybb login. I ran 3 code snippets for testing curl and they all reported it was installed.

**Comment by TsunaMoo** [comment]
This is quite strange. If you can provide me with access to it I might be able to look into it.

**Comment by sanny-io** [comment]
We ended up switching to other forum software. Thank you for your assistance, though. I'm not sure if this was a problem only for our server or what, but if it's of any help, the new software we use has a community made plugin for Steam that has been working perfectly.

I'll leave this open in case anyone else has this same issue, but you can close it whenever you'd like to.

**Comment by Fraxured** [comment]
This happened with my forum install last night except when a user went to sign in it would just redirect them to a broken page saying the site wasn't working. I'm gonna try and reinstall today and see if I still have the same issue.

**Comment by relre** [comment]
I am not getting an error but not register and login.
dispname.php enable
mybb 1.8.10

**Comment by TsunaMoo** [comment]
Well if you get an error for dispname.php then don't comment in an issue regarding login.
