### ISSUE TITLE
Option to use Email or Steam, Stop forcing redirect to already signed up users. 

### ISSUE THREAD

**Issue by ghost** [noxwyll/Steam-Login-MyBB-1.8#36]
I like the steam sign up, but it messes up things for users already signed up through email. Makes a whole new account. When a user types in wrong email and pass, it redirects them to steam. It should redirect to failed login attempt. But the user doesn't understand it's not verifying their account, it's creating a new one.  Register automatically goes to steam also. I'd rather it just go to registration. People would click sign in through steam if that's how they sign up.

If i could get help with this issue that would be great!

**Comment by ghost** [comment]
Maybe if i paid you to do this fix you could make it happen?

**Comment by TsunaMoo** [comment]
User currently dont have passwords either.
Well paying me wouldn't help.
I need a bunch for free days that i can dedicate to actually doing this.
Or find somebody to help out to get it done. -> #15 & #29

**Comment by Quintenps** [comment]
With pws you mean passwords?

**Comment by TsunaMoo** [comment]
Yes. To do this we need a form for users to fill out after returning from steam (if they dont have a pw, email set). We will need to make sure emails are unique so we could use them during login. Otherwise we need to use steam numeric ids. Probably not optimal.

**Comment by ghost** [comment]
https://github.com/stewartiee/Steam-OpenID--MyBB-/tree/version2

This actually works for Users registering with email and steam. Links steam to their email log in and bam use both to login now. I like it.

**Comment by TsunaMoo** [comment]
It depends on what you want plugin wise. As for my version it will in the future come with a option that asks users to input an email address on first login via steam.
