### ISSUE TITLE
Having issues changing the position of the button. 

### ISSUE THREAD

**Issue by cupnugget209** [noxwyll/Steam-Login-MyBB-1.8#37]
Hello I need some help changing the button position. In header_welcomeblock_guest changing the padding is not working.

**Comment by cupnugget209** [comment]
Oh I am using a theme by the way. its not the default mybb theme.

**Comment by TsunaMoo** [comment]
Yeah the problem is that most themes have different height there.
what you are looking for is in the header_welcomeblock_guest template.

**Comment by TsunaMoo** [comment]
Probably best if i turn this into a template.

**Comment by TsunaMoo** [comment]
Will be turned into an overwrite template instead of replace function.

**Comment by TsunaMoo** [comment]
Turned into dedicated template that was dramatically simplified. Edited positions so it should by default be properly positioned. Should now be considerably more easy to edit the position when needed. Resolved.
