### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by BasonTaylor** [noxwyll/Steam-Login-MyBB-1.8#38]
how do i add this to a template

**Comment by BasonTaylor** [comment]
it does not add to my new template

**Comment by TsunaMoo** [comment]
Please be more specific regarding what you want.

**Comment by BasonTaylor** [comment]
okay 2 things 1 when i have a user made adminitration it tells them to sign
in but it does not give them an option for steam login

**Comment by TsunaMoo** [comment]
You need one account for admin backend and one account for forum use atm. this may change in the future. please be patient.
