### ISSUE TITLE
Error accessing help pages

### ISSUE THREAD

**Issue by Taurvi** [noxwyll/Steam-Login-MyBB-1.8#4]
Only administrators can access help pages. When non-admins attempt, they get an error that says "You should not be here..."

When the plugin is disabled everything works again.

**Comment by TsunaMoo** [comment]
I removed a broken unused function from the plugin. I believe it has caused this.
I tested it with a non admin user and all seems fine.

**Comment by TsunaMoo** [comment]
Can you confirm it fixed?

**Comment by Taurvi** [comment]
It has been fixed. Thank you :)
