### ISSUE TITLE
Can't register, SQL internal error.

### ISSUE THREAD

**Issue by NixBoy** [noxwyll/Steam-Login-MyBB-1.8#40]
MyBB SQL Error
MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1054 - Unknown column 'loginname' in 'where clause'
Query:
SELECT * FROM mybbny_users WHERE loginname = '76561198318313333'
Please contact the MyBB Group for technical support.

http://prntscr.com/ea57r4

Thanks.

**Comment by TsunaMoo** [comment]
Please activate displaynames plugin.
