### ISSUE TITLE
Cannot Register and Profile Page

### ISSUE THREAD

**Issue by relre** [noxwyll/Steam-Login-MyBB-1.8#42]
Parse error: syntax error, unexpected '-', expecting function (T_FUNCTION) in /home/wasdzone/public_html/forum/inc/class_steam.php on line 95

**Comment by SirDabs** [comment]
Same issue trying to fix it now

**Comment by TsunaMoo** [comment]
Fixed it. Some weird -'s turned up in the code by accident.

**Comment by relre** [comment]
I am not getting an error but not register and login.
dispname.php enable
mybb 1.8.10
