### ISSUE TITLE
Usernames dont display with correct encoding.

### ISSUE THREAD

**Issue by MultiZachZ** [noxwyll/Steam-Login-MyBB-1.8#47]
We need some help, our usernames (ported from Steam) don't show correctly, here is an example.

http://carbon-castles.com/forums/member.php?action=profile&uid=58

**Comment by TsunaMoo** [comment]
Please make sure you use MyBB 1.8.8 or NEWER

**Comment by MultiZachZ** [comment]
we are on 1.8.12 and are having the issue

**Comment by TsunaMoo** [comment]
Good. Likely the reason is username being converted twice I imagine.
I would need to examine your site closely to resolve investigate.
If you are ok with that you can find me at steamcommunity/id/Tatsuto
