### ISSUE TITLE
New to MyBB, need to reposition the login button

### ISSUE THREAD

**Issue by sarahsturgeon** [noxwyll/Steam-Login-MyBB-1.8#49]
This is a simple question and I know it's not directly related to this repo, but I would really appreciate some help!

After changing themes, I don't have the Steam Login button anymore, and I don't know how to reposition it.

Any advice?

By the way, this plugin is a goddamn lifesaver. Do you have somewhere I can buy you a beer or a coffee?

**Comment by Evolocity1** [comment]
Yes, how can you add the sign into steam for another theme?

**Comment by TsunaMoo** [comment]
If the other theme has a template for header_welcomeblock_guest
Just remove it or enter this code:
```
<!-- Continuation of div(class="upper") as opened in the header template -->
		<span class="welcome">
			<a href="{$mybb->settings[\'bburl\']}/misc.php?action=steam_login">
				<img border="0" src="https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png" alt="Login through Steam" style="height: 24px;margin-bottom: -5px;margin-top: -2px;">
			</a>
		</span>
	</div>
</div>
```

**Comment by sarahsturgeon** [comment]
Hey @noxwyll , this worked before the recent MyBB update. Now when I attempt to use this snippet, the editor says there's a potential security issue with the code.

Any ideas?

Thanks for all of the help, it's greatly appreciated!
 
Edit: Looks like it was mad about accessing the MyBB settings in this line: `<a href="{$mybb->settings[\'bburl\']}/misc.php?action=steam_login">`, I replaced the accessor with my URL instead and it seems to have worked.

**Comment by TsunaMoo** [comment]
Remove the \ in front of '
