### ISSUE TITLE
Have 2 ways of register

### ISSUE THREAD

**Issue by vitt0** [noxwyll/Steam-Login-MyBB-1.8#5]
Hi there, 

I was thinking if is posible to have the Steam register system and also have the default method for register at the same time? 

From already ty for time :)

Greetings.

**Comment by TsunaMoo** [comment]
Take a look at this thing
https://github.com/stewartiee/Steam-OpenID--MyBB-/tree/version2
I am not quite sure how it works. But initally I did not want it to be that way.
Altho I think about asking for email when registering.
