### ISSUE TITLE
How would I replace the login/register button? Couldn't find it anywhere else.

### ISSUE THREAD

**Issue by blaketigges** [noxwyll/Steam-Login-MyBB-1.8#52]
Using newest version of [Flatty](https://community.mybb.com/mods.php?action=view&pid=617) and the latest version of Steam-Login-MyBB-1.8. Everything worked fine on default theme, then I added the Flatty theme and its Login and Register buttons still show up but you can click Login > then login again to get to steam login or register > I agree to get to login but how would replace both of the buttons with a "login with steam" button?

Also, sorry for my stupidity and awful writing skills, and if it is the wrong place to post this.

**Comment by TsunaMoo** [comment]
Replace any instance of the login link with
`
			<a href="{$mybb->settings[\'bburl\']}/misc.php?action=steam_login">
				<img border="0" src="https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png" alt="Login through Steam" style="height: 24px;margin-bottom: -5px;margin-top: -2px;">
			</a>`

Alternatively reset every instance of header_welcomeblock_guest template to default
