### ISSUE TITLE
Blank white page after login

### ISSUE THREAD

**Issue by reneb71** [noxwyll/Steam-Login-MyBB-1.8#54]
Hey,

Having issue when logging in. It shows white blank page after loggin

**Comment by TsunaMoo** [comment]
Make sure all required php modules are installed

**Comment by reneb71** [comment]
Hey,

Required php modules are installed.
mbstring
http://i.imgur.com/wVNJeq8.png
json
http://i.imgur.com/ZA4s404.png
Curl
http://i.imgur.com/l59biuR.png
Bcmath
http://i.imgur.com/QWzAmK4.png

Some times it works fine, and some times it gives blank page. Its like a rollercoaster
