### ISSUE TITLE
Blank site (reopen) 

### ISSUE THREAD

**Issue by reneb71** [noxwyll/Steam-Login-MyBB-1.8#55]
Hey,

Required php modules are installed.
mbstring
http://i.imgur.com/wVNJeq8.png
json
http://i.imgur.com/ZA4s404.png
Curl
http://i.imgur.com/l59biuR.png
Bcmath
http://i.imgur.com/QWzAmK4.png

Some times it works fine, and some times it gives blank page. Its like a rollercoaster

**Comment by TsunaMoo** [comment]
Sounds like issues with server itself. If its random I cant really do anything. If you got more details then maybe.

**Comment by Nyoob** [comment]
Same issue, not random for me, it just redirects to a blank page for me and others every single time

**Comment by TsunaMoo** [comment]
Server errors. Server error logs required.

**Comment by TuXEKRO** [comment]
It happens to me too. I have tried to look inside CPANEL to see if there are any errors related to the login but I can't find anything.
