### ISSUE TITLE
Endless Redirect Loop to steam login and back when going to website with force login enabled

### ISSUE THREAD

**Issue by Kaydax** [noxwyll/Steam-Login-MyBB-1.8#56]
This is an annoying bug as I want people to be logged in when the come to my fourms. Is there anyway you could fix this up. Thanks

**Comment by TsunaMoo** [comment]
When I find the time to come back and work on this. Hopefully 1 week from now when I added some functions.

**Comment by TsunaMoo** [comment]
Ok that turned out false since this is a lot to do but. Its on my list together with tos acceptance.

**Comment by Gamma000** [comment]
The cause has yet to be determined after 5 months?

**Comment by TsunaMoo** [comment]
Server errors due to missing prequisites and other versions of required elements. Errorlogs needs to be provided for any kind of debug on this. Debug only possible on a per person basis.

**Comment by Stage4000** [comment]
I am having the same issue. Please email me at Admin@Stage4000.Com

**Comment by Stage4000** [comment]
https://stage4000.com/game/info.php
