### ISSUE TITLE
Logging in problem

### ISSUE THREAD

**Issue by HumanTree92** [noxwyll/Steam-Login-MyBB-1.8#58]
When a user clicks on Create an account it takes them to my Registration Agreement page then when they accept that it takes them to the steam login page for them to finishing joining my forums. However when a user clicks on Login it asks them for a Username & Password. How would i fix this. You can see the problem here http://www.velocitientertainment.com/forum/

**Comment by TsunaMoo** [comment]
You need to replace the login form with the steam login button.

Template header_welcomeblock_guest should be:
`<a href="{$mybb->settings[\'bburl\']}/misc.php?action=steam_login"> <img border="0" src="https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png" alt="Login through Steam" style="height: 24px;margin-bottom: -5px;margin-top: -2px;"> </a>`
