### ISSUE TITLE
Guest page on login

### ISSUE THREAD

**Issue by viral32111** [noxwyll/Steam-Login-MyBB-1.8#60]
So whenever i press the Sign in through Steam button on my forum it redirects me to the steam login page, i press login then when it redirects me back to the forum it hasn't logged me in, i can still see all the guest viewer stuff.

**Comment by TsunaMoo** [comment]
Sounds like a cookie issue or missing php modules. Need more info on this.
Likely duplicate.

**Comment by Gamma000** [comment]
Same issue. I've had it working before for 5 months now all of a sudden it does this-
After signing in via Steam, redirects you back and you are not signed in. It seems like you've been having this issue since November. I rely on this as my community is based around Steam.

**Comment by TsunaMoo** [comment]
add me on steam http://steamcommunity.com/id/Tatsuto

**Comment by TsunaMoo** [comment]
server errors due to prequisites.
