### ISSUE TITLE
White page when returning from Steam Login page

### ISSUE THREAD

**Issue by sarahsturgeon** [noxwyll/Steam-Login-MyBB-1.8#63]
After logging in successfully with Steam, users are returned to the `/misc.php?action=steam_return` URL, but it never properly redirects them to the site. Just a blank white screen. No console errors.

There's a more complete URL that I'd be happy to share privately in case it contains sensitive information.

**Comment by Nyoob** [comment]
Same here

**Comment by TsunaMoo** [comment]
Sounds strange. Never had this issue. Might be something serverside. Add me on steam
steamcommunity.com/id/Tatsuto

**Comment by sarahsturgeon** [comment]
I'll add you here shortly.

I should note that I've only noticed this happening after the latest myBB update, but I'm not confident that it's the cause.

**Comment by TsunaMoo** [comment]
I think i accidentally denied the friend request. If that is the case link me to your profile.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sarahsturgeon** [comment]
steamcommunity.com/id/Phatso727 :)

**Comment by sarahsturgeon** [comment]
@noxwyll The only response I got from this issue indicated I needed to check error logs on my server host, of which there wren't any.

I've been slacking on pursuing this, but my forums are inaccessible without this thing working.
I've reached out to you on steam a couple of times but it just doesn't seem like we've been able to connect.

Do you have any other ideas on how to debug?

**Comment by TsunaMoo** [comment]
I'd like to help you fix it but without anything to go on it's just randomly guessing. Chances are low to fix anything like that.

You need the error log and php error display on.

**Comment by sarahsturgeon** [comment]
@noxwyll Here's the latest error logs!

```php
[10-Jul-2018 23:13:48 UTC] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'No OpenID Server found at http://steamcommunity.com/openid' in <snip>/inc/class_lightopenid.php:515
Stack trace:
#0 <snip>/inc/class_lightopenid.php(648): LightOpenID->discover('http://steamcom...')
#1 <snip>/inc/plugins/steamlogin.php(319): LightOpenID->authUrl()
#2 <snip>/inc/class_plugins.php(142): steam_redirect('')
#3 <snip>/inc/functions.php(887): pluginSystem->run_hooks('no_permission')
#4 <snip>/calendar.php(239): error_no_permission()
#5 {main}
  thrown in <snip>/inc/class_lightopenid.php on line 515
```

**Comment by TsunaMoo** [comment]
This is an issue with your servers connection to steam or with your API key not being valid.

**Comment by sarahsturgeon** [comment]
Sure was, my API key was expired. Thank you. 👍

**Comment by viggjona** [comment]
Eeh I have this problem atm. I have tried with another accounts api key, with my api key. Revoked and I made it a new one like 10 times.  I am using hexanes web services.

**Comment by Morgan-Moon** [comment]
I am also having the same issue

**Comment by rubiksw** [comment]
In my case the API key was expired. Creating a new key worked for me.
https://steamcommunity.com/dev/registerkey
