### ISSUE TITLE
Error when trying to register

### ISSUE THREAD

**Issue by CubXD** [noxwyll/Steam-Login-MyBB-1.8#67]
This isn't a giant issue but if left unfixed could turn into one. When someone tries to register using steam login on my forum they get the error listed below. This happens only when the user has a public IP address using the IPv6 Protocol. My assumption is the obvious one, that since IPv6 addresses are larger than IPv4, the addon must've only be meant to support IPv4 since during the last update not too many people had IPv6. But IPv6 is beginning to become standard across ISP's so this would need to be ironed out soon. (I know this is an error with registering via steam specifically as the same user who got this error has created an account before)

[Error]https://i.imgur.com/PPJl4O2.png(url)

**Comment by TsunaMoo** [comment]
This seems more like a issue with default MYBB.
If it doesnt happen without the plugin then I can take a look.
