### ISSUE TITLE
MyBB 1.8.17 - Can't login through plugin.

### ISSUE THREAD

**Issue by fizioterapia** [noxwyll/Steam-Login-MyBB-1.8#68]
Hello, with the new version of MyBB, users of my boards are unable to login or register using this plugin.
It works like, on older versions. It redirects to Steam Login using OpenID and later it redirects again to my website, but i wasn't logged in. In Admin Control Panel also there weren't any users registered using this addon.

**Comment by TsunaMoo** [comment]
check your cookie paths
