### ISSUE TITLE
Question: Both ways of registration

### ISSUE THREAD

**Issue by ghost** [noxwyll/Steam-Login-MyBB-1.8#7]
Does it FULLY replace registration, or does it allow registration in both ways(Normal & Steam) Like in vBulletin?

**Comment by TsunaMoo** [comment]
fully replaces well at least as much as u can claim its the case. Normal accs are made and used for acp steamacss for frontend.

**Comment by TsunaMoo** [comment]
try version 2 of the repository this is a fork of.
