### ISSUE TITLE
No OpenID Server Found

### ISSUE THREAD

**Issue by HumanTree92** [noxwyll/Steam-Login-MyBB-1.8#70]
Website:
http://www.velocitientertainment.com/forum/

Error: 
[17-Apr-2019 05:51:01 UTC] PHP Fatal error:  Uncaught ErrorException: No OpenID Server found at http://steamcommunity.com/openid in /home/humantree92/public_html/forum/inc/class_lightopenid.php:515
Stack trace:
#0 /home/humantree92/public_html/forum/inc/class_lightopenid.php(648): LightOpenID->discover('http://steamcom...')
#1 /home/humantree92/public_html/forum/inc/plugins/steamlogin.php(369): LightOpenID->authUrl()
#2 /home/humantree92/public_html/forum/inc/class_plugins.php(142): steam_redirect('')
#3 /home/humantree92/public_html/forum/member.php(786): pluginSystem->run_hooks(Array)
#4 {main}
  thrown in /home/humantree92/public_html/forum/inc/class_lightopenid.php on line 515

**Comment by TsunaMoo** [comment]
Steam, was down.
